# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class C9s < Formula
  desc "Terminal dashboard for Claude Code sessions"
  homepage "https://github.com/stefanoguerrini/c9s"
  version "0.0.1"
  license "MIT"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/StefanoGuerrini/c9s/releases/download/v0.0.1/c9s_0.0.1_darwin_amd64.tar.gz"
      sha256 "b626bd0bcbde256551c61144a422bfef90a6037269ebc924eac4446201067e5e"

      define_method(:install) do
        bin.install "c9s"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/StefanoGuerrini/c9s/releases/download/v0.0.1/c9s_0.0.1_darwin_arm64.tar.gz"
      sha256 "a6939ab07a027eebd6e9c867983d9e0028f22556eb0bf615b3c4c313870657c6"

      define_method(:install) do
        bin.install "c9s"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/StefanoGuerrini/c9s/releases/download/v0.0.1/c9s_0.0.1_linux_amd64.tar.gz"
      sha256 "4522608863a31497aefccebf9327ca3a6c4ebd413436a19901cd5330799753c2"
      define_method(:install) do
        bin.install "c9s"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/StefanoGuerrini/c9s/releases/download/v0.0.1/c9s_0.0.1_linux_arm64.tar.gz"
      sha256 "66c253bc452c34118a2858ed8cbaad30a28b8bcd273811d51f36c9a17be517b0"
      define_method(:install) do
        bin.install "c9s"
      end
    end
  end

  test do
    system "#{bin}/c9s", "--version"
  end
end
